### ISSUE TITLE
Network.warmup() crashes on gradle/android app

### ISSUE THREAD

**Issue by geckogecko** [ArkEcosystem/ark-java#20]
> Caused by: groovy.lang.MissingPropertyException: No such property: ip for class: io.ark.core.Peer
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$NoParamSite.callConstructor(ConstructorSite.java:127)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
at io.ark.core.Peer.create(Peer.groovy:24)

**Comment by Guppster** [comment]
What version of the library are you using? Are you using your own instance of Network? 
Network.mainnet & Network.devnet are both successfully warmed up in the test suite.
 
Take a look at [the network test file](../../ark-java/blob/master/src/test/groovy/NetworkTest.groovy) to see how those methods should be used

**Comment by geckogecko** [comment]
I used the `0.3 jar` with an android app and `Network.mainnet`

**Comment by dafty** [comment]
@geckogecko Can you try reproducing with the latest 1.0.0 release?

**Comment by geckogecko** [comment]
@dafty I will try. 
What I did was just creating a new android project -> adding the jar -> and then I called Network.warmup() in onCreate()
